# vim: ft=yaml
os:
  - linux
  # OSX is not supported yet
  #- osx

language: bash

sudo: required

env:
  - TRAVIS_BASH_VERSION="4.1" TRAVIS_ZSH_VERSION="5.0.0" TRAVIS_FISH_VERSION="2.2.0" TRAVIS_GIT_VERSION="1.8.0"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./tests/test-utils/installs/install-linux-deps.sh; fi;
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./tests/test-utils/installs/install-osx-deps.sh; fi;

install:
  - curl -sL https://git.io/vV4yE | sh
  - source ~/.bashrc
  - echo 'PEARL_PACKAGES["fonts"]="https://github.com/pearl-hub/fonts.git"' >> $HOME/.config/pearl/pearl.conf
  - echo "PEARL_PACKAGES[test]=\"${PWD}\"" >> ~/.config/pearl/pearl.conf

script:
  - ./tests/integ-tests/integ-tests.sh
